version: '3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: gqcv-base:latest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cecc:latest
    ports:
      - "5443:443"
    volumes:
      - ./data:/gqcv/data
    depends_on:
      - base
    environment:
      - NAME=CECC
    restart: "no"
