# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Copy requirements to temp folder
COPY requirements.txt /tmp

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
