version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./data:/cecc/data
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: cecc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
