version: '3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: cecc-base:latest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cecc:latest
    ports:
      - "8443:443"
    volumes:
      - ./data:/cecc/data
    depends_on:
      - base
    environment:
      - NAME=CECC
    restart: no
